spring.application.name=demo

server.port=8081

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/expenses

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.type=redis

# JWT
jwt.secret=mysecretkeymysecretkeymysecretkey12345
jwt.expiration=3600000

# Error Messages
server.error.include-message=always

# Actuator
management.endpoints.web.exposure.include=*

# Logging
logging.level.org.springframework.security=DEBUG